package business.banking.dgnravepay.wallet.enums;



public enum IndustrySubCategory {
    // AGRICULTURE
    CROP_PRODUCTION,
    LIVESTOCK,
    FORESTRY,
    FISHING_AQUACULTURE,



    // MINING
    CRUDE_PETROLEUM_GAS,
    COAL_MINING,
    METAL_ORES,
    QUARRYING,

    // MANUFACTURING
    FOOD_BEVERAGES,
    TEXTILES,
    APPAREL,
    WOOD_PRODUCTS,
    PULP_PAPER,
    CHEMICAL_PHARMACEUTICALS,
    NON_METALLIC_MINERALS,
    BASIC_METALS,
    PLASTIC_RUBBER,
    ELECTRICAL_ELECTRONICS,
    MOTOR_VEHICLES,

    // CONSTRUCTION
    BUILDING_CONSTRUCTION,
    CIVIL_ENGINEERING,
    SPECIALIZED_CONSTRUCTION,

    // UTILITIES
    ELECTRICITY,
    GAS,
    STEAM_AIR_CONDITIONING,
    WATER_SUPPLY,
    SEWERAGE_WASTE,

    // INFORMATION
    TELECOMMUNICATIONS,
    BROADCASTING,
    PUBLISHING,
    MOTION_PICTURES_MUSIC,
    IT_SERVICES,

    // FINANCIAL
    COMMERCIAL_BANKING,
    MICROFINANCE,
    INSURANCE,
    PENSION,
    CAPITAL_MARKET,

    // TRADE
    WHOLESALE,
    RETAIL,
    VEHICLE_REPAIR,

    // REAL ESTATE
    PROPERTY_DEVELOPMENT,
    REAL_ESTATE_AGENCY,
    FACILITY_MANAGEMENT,

    // PROFESSIONAL
    LEGAL,
    ACCOUNTING,
    ARCHITECTURE_ENGINEERING,
    ADVERTISING,
    VETERINARY,

    // TRANSPORT
    ROAD_TRANSPORT,
    AIR_TRANSPORT,
    WATER_TRANSPORT,
    WAREHOUSING,

    // HOSPITALITY
    ACCOMMODATION,
    FOOD_BEVERAGE,
    TRAVEL_AGENCY,

    // EDUCATION & HEALTH
    SCHOOLS,
    HOSPITALS,
    DIAGNOSTIC,
    SOCIAL_WORK,

    // ARTS
    GAMBLING,
    CREATIVE_ARTS,
    SPORTS_AMUSEMENT,

    // ADMIN
    RENTAL_LEASING,
    EMPLOYMENT_AGENCY,
    SECURITY,
    OFFICE_SUPPORT
}
