package business.banking.dgnravepay.wallet.enums;


public enum IndustryCategory {
    AGRICULTURE,
    MINING,
    MANUFACTURING,
    CONSTRUCTION,
    UTILITIES,
    INFORMATION_COMMUNICATION,
    FINANCIAL_INSURANCE,
    TRADE,
    REAL_ESTATE,
    PROFESSIONAL_TECHNICAL,
    TRANSPORT_STORAGE,
    HOSPITALITY_TOURISM,
    EDUCATION_HEALTH,
    ARTS_RECREATION,
    ADMINISTRATIVE_SUPPORT
}
