package business.banking.dgnravepay.wallet.enums;



public enum Occupation {

    /* =========================
       AGRICULTURE → CROP_PRODUCTION
       ========================= */
    FARMER,
    AGRONOMIST,
    CROP_SCIENTIST,
    AGRICULTURAL_TECHNICIAN,
    FARM_WORKER,

    /* =========================
       AGRICULTURE → LIVESTOCK
       ========================= */
    LIVESTOCK_FARMER,
    VETERINARY_TECHNICIAN,
    ANIMAL_BREEDER,
    POULTRY_FARMER,

    /* =========================
       AGRICULTURE → FISHING_AQUACULTURE
       ========================= */
    FISHERMAN,
    AQUACULTURE_TECHNICIAN,
    FISH_FARM_MANAGER,

    /* =========================
       MINING → CRUDE_PETROLEUM_GAS
       ========================= */
    PETROLEUM_ENGINEER,
    DRILLING_ENGINEER,
    RIG_TECHNICIAN,
    OIL_GAS_OPERATOR,
    MINER,
    MINING_ENGINEER,
    GEOLOGIST,
    OIL_RIG_WORKER,
    GAS_TECHNICIAN,
    REFINERY_OPERATOR,

    /* =========================
       MANUFACTURING → FOOD_BEVERAGES
       ========================= */
    FOOD_PROCESSING_TECHNICIAN,
    QUALITY_CONTROL_INSPECTOR,
    PRODUCTION_SUPERVISOR,

    /* =========================
       MANUFACTURING → TEXTILES
       ========================= */
    TEXTILE_TECHNICIAN,
    GARMENT_PRODUCTION_WORKER,
    PATTERN_MAKER,

    /* =========================
       CONSTRUCTION → BUILDING_CONSTRUCTION
       ========================= */
    CIVIL_ENGINEER,
    CONSTRUCTION_FOREMAN,
    MASON,
    CARPENTER,
    ELECTRICIAN,
    PLUMBER,
    STRUCTURAL_ENGINEER,
    CONSTRUCTION_MANAGER,
    ARCHITECT,
    BRICKLAYER,
    PAINTER,
    ROOFER,
    SURVEYOR,


    /* =========================
       INFORMATION → IT_SERVICES
       ========================= */
    SOFTWARE_ENGINEER,
    BACKEND_DEVELOPER,
    FRONTEND_DEVELOPER,
    FULL_STACK_DEVELOPER,
    MOBILE_APP_DEVELOPER,
    GAME_DEVELOPER,
    DATA_SCIENTIST,
    DATA_ANALYST,
    DATA_ENGINEER,
    DEVOPS_ENGINEER,
    SITE_RELIABILITY_ENGINEER,
    CLOUD_ENGINEER,
    CLOUD_ARCHITECT,
    CYBERSECURITY_ANALYST,
    INFORMATION_SECURITY_OFFICER,
    NETWORK_ENGINEER,
    SYSTEM_ADMINISTRATOR,
    DATABASE_ADMINISTRATOR,
    IT_SUPPORT_SPECIALIST,
    QA_ENGINEER,
    TEST_AUTOMATION_ENGINEER,
    PRODUCT_MANAGER,
    TECHNICAL_WRITER,


    /* =========================
       FINANCIAL → COMMERCIAL_BANKING
       ========================= */
    BANKER,
    CREDIT_ANALYST,
    LOAN_OFFICER,
    COMPLIANCE_OFFICER,
    RISK_ANALYST,
    TELLER,
    CREDIT_OFFICER,
    FINANCIAL_ANALYST,
    INVESTMENT_ANALYST,
    PORTFOLIO_MANAGER,
    ACCOUNTANT,
    CHARTERED_ACCOUNTANT,
    AUDITOR,
    TAX_CONSULTANT,
    /* =========================
       FINANCIAL → INSURANCE
       ========================= */
    INSURANCE_UNDERWRITER,
    CLAIMS_OFFICER,
    ACTUARY,
    INSURANCE_AGENT,
    /* =========================
       TRADE → RETAIL
       ========================= */
    SHOP_OWNER,
    SALES_ASSOCIATE,
    STORE_MANAGER,
    MERCHANDISER,

    /* =========================
       TRANSPORT → ROAD_TRANSPORT
       ========================= */
    TRUCK_DRIVER,
    DELIVERY_DRIVER,
    BUS_DRIVER,
    TAXI_DRIVER,
    RIDE_SHARE_DRIVER,
    PILOT,
    FLIGHT_ATTENDANT,
    AIR_TRAFFIC_CONTROLLER,
    SHIP_CAPTAIN,
    SEAFARER,
    DOCK_WORKER,


    /* =========================
       EDUCATION → SCHOOLS
       ========================= */
    UNIVERSITY_LECTURER,
    COLLEGE_LECTURER,
    RESEARCH_SCIENTIST,
    POSTDOCTORAL_RESEARCHER,
    SECONDARY_SCHOOL_TEACHER,
    PRIMARY_SCHOOL_TEACHER,
    EARLY_CHILDHOOD_EDUCATOR,
    SPECIAL_EDUCATION_TEACHER,
    TEACHING_ASSISTANT,
    SCHOOL_ADMINISTRATOR,
    PRINCIPAL,
    LIBRARIAN,
    /* =========================
       HEALTH → HOSPITALS
       ========================= */
    MEDICAL_DOCTOR,
    GENERAL_PRACTITIONER,
    SURGEON,
    PHYSICIAN,
    DENTIST,
    ORTHODONTIST,
    NURSE,
    MIDWIFE,
    PHARMACIST,
    PHARMACY_TECHNICIAN,
    MEDICAL_LAB_TECHNICIAN,
    RADIOGRAPHER,
    ANESTHETIST,
    PARAMEDIC,
    EMERGENCY_MEDICAL_TECHNICIAN,
    PHYSIOTHERAPIST,
    OCCUPATIONAL_THERAPIST,
    PSYCHOLOGIST,
    PSYCHIATRIST,
    COUNSELOR,
    PUBLIC_HEALTH_OFFICER,
    EPIDEMIOLOGIST,
    VETERINARIAN,

    /* =========================
       HOSPITALITY → ACCOMMODATION
       ========================= */
    HOTEL_MANAGER,
    HOTEL_RECEPTIONIST,
    CONCIERGE,
    CHEF,
    SOUS_CHEF,
    COOK,
    BAKER,
    PASTRY_CHEF,
    WAITER,
    SERVER,
    BARTENDER,
    BARISTA,
    CATERING_MANAGER,
    TOUR_GUIDE,
    TRAVEL_AGENT,
    EVENT_PLANNER,


    /* =========================
       ARTS → CREATIVE_ARTS
       ========================= */
    GRAPHIC_DESIGNER,
    UI_UX_DESIGNER,
    INDUSTRIAL_DESIGNER,
    FASHION_DESIGNER,
    TEXTILE_DESIGNER,
    ILLUSTRATOR,
    PHOTOGRAPHER,
    VIDEOGRAPHER,
    VIDEO_EDITOR,
    FILM_DIRECTOR,
    FILM_PRODUCER,
    SCREENWRITER,
    ACTOR,
    VOICE_ACTOR,
    MUSICIAN,
    SINGER,
    COMPOSER,
    DJ,
    SOUND_ENGINEER,
    JOURNALIST,
    EDITOR,
    NEWS_ANCHOR,
    CONTENT_CREATOR,
    INFLUENCER,


    /* =========================
       ADMIN → OFFICE_SUPPORT
       ========================= */
    OFFICE_ADMINISTRATOR,
    OFFICE_MANAGER,
    EXECUTIVE_ASSISTANT,
    PERSONAL_ASSISTANT,
    SECRETARY,
    RECEPTIONIST,
    DATA_ENTRY_CLERK,
    RECORDS_OFFICER,
    PROCUREMENT_OFFICER,
    INVENTORY_MANAGER,
}
